### ISSUE TITLE
different J1 - Ask for support

### ISSUE THREAD

**Issue by ddubberc** [randomplum/autoliv_nv3_uvc#2]
Hi, much appreciate your work!

I have an NV3 with different b2b Connector: in the project uses J1 on pos 13: Molex 52991-0408 (2x20 pin), I see 
Molex 52991-0808 (2x40 pin). I cant find straight mapping to the pinout.

I'd like to ask for support for the 80pin board. Tell if I can give any help with this.

Thanks.
![2024-02-13-135747_770x726_scrot](https://github.com/randomplum/autoliv_nv3_uvc/assets/159913019/e57287e4-01b7-47db-8967-1548ab74a2bb)

**Comment by randomplum** [comment]
Hi,

I’ve designed the board to interface with the sensor directly, it basically replaces the board in your photo.

**Comment by randomplum** [comment]
![IMG_0104](https://github.com/randomplum/autoliv_nv3_uvc/assets/58212048/f96f298b-1f58-4fe4-93fa-7f6b612a90d2)
This is how it looks assembled

**Comment by ddubberc** [comment]
Thank you! Now I see. I am committed to build at least 2 of this. More questions may come...
